name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Flutter pub get
        run: flutter pub get
      - name: Format check
        run: |
          dart format --output=none --set-exit-if-changed .
      - name: Analyze
        run: dart analyze
      - name: Test with coverage
        run: flutter test --coverage
      - name: Upload coverage to Codecov
        if: ${{ success() }}
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
          fail_ci_if_error: true

